---
- name: CONFIGURE IPv6 ADDRESSING
  hosts: csr
  gather_facts: false
  connection: local

  tasks:
   - name: SET IPv6 ADDRESS 
     ios_config:
       parents: "interface GigabitEthernet1"
       lines:
         - description IPv6 ADDRESS FROM ANSIBLE
         - ipv6 address 2001:db8:acad:1::107/64
         - ipv6 address fe80::1:107 link-local

   - name: SHOW IPv6 INTERFACE BRIEF 
     ios_command:
       commands:
         - show ipv6 interface brief
     register: output

   - name: SAVE OUTPUT ./ios_configurations/
     copy: 
       content: "{{ output.stdout[0] }}"
       dest: "ios_configurations/IPv6_output_{{ inventory_hostname }}.txt"
